### ISSUE TITLE
CloudWatch: publish_lambda_error() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by vigowei** [atlassian/localstack#106]
This function is defined and used in cloudwatch_util.py. The line referencing this function also passes in `time_before`, maybe consider adding it to the definition or pass it in as one of the **kwargs.

**Comment by whummer** [comment]
Thanks for reporting, this bug is fixed in commit 85215efe555eaf366fa0291a88e18ee20a0654d8 (integration tests have been extended to cover the functionality around the Lambda `Errors` metric)
