### ISSUE TITLE
Dies when deploying simple example

### ISSUE THREAD

**Issue by vangorra** [atlassian/localstack#109]
Haven't been able to test much as localstack fails deploying a super simple cloudformation stack. The documentation is non-existent, is localstack suppose to support deployment of cloudformation stacks?

## Get docker running
- `docker pull atlassianlabs/localstack`
- `docker run -p 8080:8080 -p 4567:4567 -p 4568:4568 -p 4569:4569 -p 4570:4570 -p 4571:4571 -p 4572:4572 -p 4573:4573 -p 4574:4574 -p 4575:4575 -p 4576:4576 -p 4577:4577 -p 4578:4578 -p 4579:4579 -p 4580:4580 -p 4581:4581 -p 4582:4582 atlassianlabs/localstack`

## Deploy the code
- `git clone https://github.com/awslabs/serverless-application-model`
- `cd serverless-application-model/examples/2016-10-31/hello_world`
- `AWS_ACCESS_KEY_ID="ID" AWS_SECRET_ACCESS_KEY="KEY" aws --region us-west-1 --endpoint-url http://localhost:4581 cloudformation deploy --template-file template.yaml --stack-name A1`

The following error is then repeated several times:
```
ERROR:localstack.mock.generic_proxy:Error forwarding request: global name 'content' is not defined
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/mock/generic_proxy.py", line 93, in forward
    data=data, headers=forward_headers, return_forward_info=True)
  File "/opt/code/localstack/localstack/mock/proxy/cloudformation_listener.py", line 119, in update_cloudformation
    return create_change_set(req_data)
  File "/opt/code/localstack/localstack/mock/proxy/cloudformation_listener.py", line 66, in create_change_set
    response = make_response('CreateChangeSet', '<Id>%s</Id>' % cs_arn)
  File "/opt/code/localstack/localstack/mock/proxy/cloudformation_listener.py", line 46, in make_response
    op_name=operation_name, uid=uuid.uuid4(), content=content)
NameError: global name 'content' is not defined
```

## My Environment
Ubuntu 17.04
Docker 1.12.6

**Comment by whummer** [comment]
Thanks for reporting. This is fixed in commit 0a4ac49744edf1105387d24538f53445622dae82 , the Docker image has been updated. Please re-open if the problem persists.
