### ISSUE TITLE
Run Lambda without being in a Docker container

### ISSUE THREAD

**Issue by aymericbeaumet** [atlassian/localstack#110]
Hey @whummer,

Here is the issue for tracking and discussing this PR: https://bitbucket.org/atlassian/localstack/pull-requests/81/run-lambda-without-being-in-a-docker/diff_

***

I have the constraint to run LocalStack on CircleCI. I made the technical decision to build a Docker image based on https://hub.docker.com/_/amazonlinux/, to be as close as possible to the production runtime environment with AWS Lambda.

I run LocalStack in that docker image without privileged permissions, so I cannot execute Docker containers. CircleCI allows me to run remote containers though (see: https://circleci.com/docs/2.0/building-docker-images).

To that end I made a pull request to offer a way to run Lambda without mounting the volume, which is not available with remote containers. The performance impact for local containers is minimal. _Maybe this could be configurable depending whether the docker host is distant._

Note that I commented the ping command (to the Docker bridge IP). It does not work when being outside of a Docker container. _I am not sure why this ping is in the use_docker function, and not in the in_docker function._ Did I miss something?

**Comment by whummer** [comment]
PR merged: https://bitbucket.org/atlassian/localstack/pull-requests/81/run-lambda-without-being-in-a-docker/diff Thanks!
