### ISSUE TITLE
Sns publishing to lambda returns unexpected protocol "lambda"

### ISSUE THREAD

**Issue by jayeszee** [atlassian/localstack#111]
Hi all, I'm basically setting up lambda to receive topic pushes from sns. However, it seems like the sns listener doesn't know what the protocol "lambda" is. Any idea why this isn't working or is this feature not yet implemented?

What I did:
1. aws sns create-topic ...
2. aws lambda create-function ...
3. aws sns subscribe --protocol lambda ...
4. aws sns publish ...

and I get this error:
localstack_1  | WARNING:localstack.mock.proxy.sns_listener:Unexpected protocol "lambda" for SNS subscription

**Comment by whummer** [comment]
Thanks for reporting @jayeszee , this is fixed in commit 24d96be6be7da3d32a09ab11d1f2e4297a1f4a1b . The latest Docker image is being built and pushed. Closing this issue now, please feel free to re-open if the problem persists. Thanks
