### ISSUE TITLE
Lambda argcount check fails for decorated functions

### ISSUE THREAD

**Issue by vigowei** [atlassian/localstack#115]
There is [a check](https://github.com/atlassian/localstack/blob/master/localstack/mock/apis/lambda_api.py#L255) in lambda_api.py to ensure that the number of arguments for a function is 2. 

For a _decorated_ function, the function object points at its wrapper so this always raises `Expected handler function with 2 parameters, found 0`. 

For example if we upload a function with `my_lambda_handler`, which is decorated by `wrapper` :

```
>>>lambda_handler = handler_module.__dict__['my_lambda_handler']
>>>lambda_handler
<function wrapper at 0x10d47bd70>
>>>lambda_handler.__code__.co_argcount
0
```

I was able to get around this issue by removing the `argcount == 2` check.

**Comment by whummer** [comment]
Thanks for reporting, this is fixed in commit b8180317e4b710ca85479d88abed6b66d800c9f2
