### ISSUE TITLE
pip install fails. 

### ISSUE THREAD

**Issue by ruimaranhao** [atlassian/localstack#128]
This is the stacktrace I am getting. Any ideas what is going on?

> Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python2.7/site-packages (from Jinja2>=2.4->flask==0.10.1->localstack)
> Requirement already satisfied: futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" in /usr/local/lib/python2.7/site-packages (from s3transfer<0.2.0,>=0.1.9->awscli==1.11.86->localstack)
> Requirement already satisfied: pyasn1>=0.1.3 in /usr/local/lib/python2.7/site-packages (from rsa<=3.5.0,>=3.1.2->awscli==1.11.86->localstack)
> Installing collected packages: subprocess32-ext, localstack
> 
> Cleaning up...
> Exception:
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
>     status = self.run(options, args)
>   File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
>     prefix=options.prefix_path,
>   File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
>     **kwargs
>   File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
>     self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
>   File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
>     isolated=self.isolated,
>   File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
>     clobber(source, lib_dir, True)
>   File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 323, in clobber
>     shutil.copyfile(srcfile, destfile)
>   File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
>     with open(dst, 'wb') as fdst:
> IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/_posixsubprocess.so'

**Comment by whummer** [comment]
> IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/_posixsubprocess.so'

Looks like this could be an issue with filesystem permissions. Please make sure that your local user has write access to the pip installation directory. Can you install any other pip packages? E.g., what happens if you run `pip install subprocess32`?

To check the file permissions, the output of the following command should look similar to this (note the `drwxr-xr-x` part):
```
$ ls -la /usr/local/lib/python2.7/site-packages/
...
drwxr-xr-x  520 <your_username>  <your_usergroup>   17680 Jun  7 07:23 .
...
```

**Comment by ruimaranhao** [comment]
Thanks! All good.
