### ISSUE TITLE
Add randomized error injection (read/write throttles) for Kinesis and DynamoDB mocks

### ISSUE THREAD

**Issue by whummer** [atlassian/localstack#13]
Based on #12 which added binary support (yes/no) for injecting Kinesis errors, we should add a configuration feature to inject indeterministic/random errors.
The same feature should also be applied for simulating DynamoDB read/write throttles.
In both cases, we can introduce `ERROR_PROBABILITY` config variables in the range [0,1] which define the probability for the framework to inject throughput exceeded exceptions.

**Comment by goodmanship** [comment]
Changing this only address kinesis errors. New issue for DDB errors: #17
