### ISSUE TITLE
virtualenv setup fails on MacOS 10.12.5

### ISSUE THREAD

**Issue by striiinger** [atlassian/localstack#130]
`pip install localstack `
fails for me when virtualenv setup occurs. Stack trace is:

>   copying build/lib/localstack/utils/testutil.py -> build/bdist.macosx-10.12-x86_64/wheel/localstack/utils
>   /bin/sh: virtualenv: command not found
>   make[1]: *** [setup-venv] Error 127
>   make: *** [install] Error 2
>   make setup-venv && \
>   		make install-libs && \
>   		make compile
>   (test `which virtualenv` || pip install --user virtualenv) && \
>   		(test -e .venv || virtualenv  .venv) && \
>   		(. .venv/bin/activate && pip install --upgrade pip) && \
>   		(test ! -e requirements.txt || (. .venv/bin/activate; pip install six==1.10.0 ; pip install -r requirements.txt))
>   Collecting virtualenv
>     Downloading virtualenv-15.1.0-py2.py3-none-any.whl (1.8MB)
>   Installing collected packages: virtualenv
>   Successfully installed virtualenv-15.1.0
>   
>   Traceback (most recent call last):
>     File "<string>", line 1, in <module>
>     File "/private/var/folders/73/8h60_drd3tx9426pnqvkmxtc0000gn/T/pip-build-Nw5DRe/localstack/setup.py", line 105, in <module>
>       "Topic :: Software Development :: Testing",
>     File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
>       dist.run_commands()
>     File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
>       self.run_command(cmd)
>     File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
>       cmd_obj.run()
>     File "/usr/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 215, in run
>       self.run_command('install')
>     File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
>       self.distribution.run_command(command)
>     File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
>       cmd_obj.run()
>     File "/usr/local/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
>       return orig.install.run(self)
>     File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 575, in run
>       self.run_command(cmd_name)
>     File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
>       self.distribution.run_command(command)
>     File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
>       cmd_obj.run()
>     File "/private/var/folders/73/8h60_drd3tx9426pnqvkmxtc0000gn/T/pip-build-Nw5DRe/localstack/setup.py", line 57, in run
>       do_make_install()
>     File "/private/var/folders/73/8h60_drd3tx9426pnqvkmxtc0000gn/T/pip-build-Nw5DRe/localstack/setup.py", line 37, in do_make_install
>       raise e
>   subprocess.CalledProcessError: Command 'make install' returned non-zero exit status 2
>   
>   ----------------------------------------
>   Failed building wheel for localstack
>   Running setup.py clean for localstack

`pip install virtualenv` reports that it is installed in $HOME/Library/Python/2.7/lib/python/site-packages, but "virtualenv" is not on the path, nor in this directory - it contains virtualenv.py

**Comment by striiinger** [comment]
`pip uninstall virtualenv`
`sudo pip install virtualenv`

resolves this, not sure why the unprivileged pip install failed to create /usr/local/bin/virtualenv

**Comment by whummer** [comment]
Thanks for reporting. I'm glad it's working now, although it seems a bit weird that apparently `virtualenv` was in fact installed successfully as part of `pip install localstack`:
```
Installing collected packages: virtualenv
Successfully installed virtualenv-15.1.0
```

I'm closing this one as resolved, but feel free to re-open if you find out more details about the error. (Ideally, if you could provide a set of commands to reproduce the issue, then we can look into it). Thanks

**Comment by molteninjabob** [comment]
I'm trying to install localstack for the first time and have run into this exact same issue. However, I tried installing with sudo and this did not resolve the problem. When I run `pip install localstack` I get the following output:

`/bin/sh: virtualenv: command not found
  make[1]: *** [setup-venv] Error 127
  make: *** [install] Error 2
  make setup-venv && \
  		make install-libs && \
  		make compile
  (test `which virtualenv` || pip install --user virtualenv) && \
  		(test -e .venv || virtualenv  .venv) && \
  		(. .venv/bin/activate && pip install --upgrade pip) && \
  		(test ! -e requirements.txt || (. .venv/bin/activate; pip install six==1.10.0 ; pip install -r requirements.txt))
  Requirement already satisfied: virtualenv in /Users/bbolton/Library/Python/2.7/lib/python/site-packages

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/tg/_k2v4n895m5bcv8_cds3q4d19x_8bc/T/pip-build-cnZNoU/localstack/setup.py", line 102, in <module>
      "Topic :: Software Development :: Testing",
    File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 215, in run
      self.run_command('install')
    File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
      return orig.install.run(self)
    File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 575, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/private/var/folders/tg/_k2v4n895m5bcv8_cds3q4d19x_8bc/T/pip-build-cnZNoU/localstack/setup.py", line 57, in run
      do_make_install()
    File "/private/var/folders/tg/_k2v4n895m5bcv8_cds3q4d19x_8bc/T/pip-build-cnZNoU/localstack/setup.py", line 37, in do_make_install
      raise e
  subprocess.CalledProcessError: Command 'make install' returned non-zero exit status 2

  ----------------------------------------
  Failed building wheel for localstack
  Running setup.py clean for localstack
Failed to build localstack
Installing collected packages: localstack
  Running setup.py install for localstack ... done
Successfully installed localstack-0.6.0.2`

**Comment by molteninjabob** [comment]
It seems that virtualenv cannot rely on `pip install localstack` for installation. I had to uninstall localstack, then `pip install virtualenv` on its own. THEN, localstack installed successfully.
