### ISSUE TITLE
Connection Aborted Error when creating a Lambda function

### ISSUE THREAD

**Issue by mateenrehan** [atlassian/localstack#132]
Hi, I am new to localstack and I installed localstack using pip install localstack. 
I even created a lambda function and created a zip file for that function but when I try to invoke that function using `aws --endpoint-url=http://localhost:4574 lambda create-function --function-name=f --runtime=python2.7 --role=r1 --handler=lambda.handler --zip-file fileb://lambda.zip` it given `('Connection aborted.', error(61, 'Connection refused'))`. Is there a step which I am missing, also I am using a MacOS.

**Comment by whummer** [comment]
Hi @mateenrehan , thanks for reporting. Please note that after installing LocalStack (i.e., downloading all the libraries and dependencies), you will also have to *start* it (i.e., run the actual server processes that provide the API functionality).

You can choose to either 1) start it on your local machine (run `localstack infra` in your terminal) or 2) run it in a Docker container. For the second option, you would actually have to clone the repository and then run `make docker-run`. In the near future we plan to add an option for Docker to the `localstack` command, to make this a bit easier. Thanks

**Comment by mateenrehan** [comment]
Thanks a lot @whummer I was able to run the docker machine by `make docker-run` and then was able to invoke the lambda function. 
I think we should have some good documentation so that a beginner can create and run lambda functions easily.

**Comment by whummer** [comment]
Thanks, I've updated the documentation to make this more clear.
