### ISSUE TITLE
Randomized errors for dynamodb mock

### ISSUE THREAD

**Issue by goodmanship** [atlassian/localstack#17]
Add a way to throw errors randomly for ddb read/writes for testing purposes

See #13 
The same feature should also be applied for simulating DynamoDB read/write throttles.
In both cases, we can introduce ERROR_PROBABILITY config variables in the range [0,1] which define the probability for the framework to inject throughput exceeded exceptions.

**Comment by whummer** [comment]
Added in 3043a2fb2675e02bfbb5268c5f7d95a5390983b2
