### ISSUE TITLE
Use lambci/docker-lambda for local lambda execution?

### ISSUE THREAD

**Issue by wcurrie** [atlassian/localstack#27]
Feel free to close this but might be worth considering using https://github.com/lambci/docker-lambda to execute lambdas. Seems they dumped the filesystem of a live lambda and made a container out of it. Neat.

**Comment by whummer** [comment]
Thanks for the suggestion, this definitely looks like a neat solution. It might be worthwhile looking into this, especially if/when we start supporting Node/Java lambdas (currently only Python Lambdas are supported), and to support full parity with the AWS environment.

There are some other issues and feature requests which probably have higher priority, but I would be more than happy to accept a pull request that adds an integration with `lambci/docker-lambda`.

**Comment by whummer** [comment]
An initial version of Docker-based Lambda execution is now available. Can you please try to run the following commands from the repository root:
```
git pull
docker pull atlassianlabs/localstack
make test-docker
```

You will notice that the output of the last commands contains a few lines like this:
```
docker run ... lambci/lambda:python2.7 "handler.handler"
...
docker run ... lambci/lambda:nodejs "handler.handler"
```

If the test runs successfully, then you should be good to start *LocalStack* in Docker and run your own custom Lambda function tests against it (only Node.js and Python are currently supported):
```
make docker-run
```

Please report back if that works for you (plus your environment details, if it does not work). Thanks.

**Comment by singledigit** [comment]
I tried this today. I am able to get the lambda to run a simple function
```javascript
exports.handler = function(event, context, callback){
   callback(null, "works");
}
```
But am getting an error
```
init handler error: TypeError
    at exports.handler (/var/task/read.js:2:11)
```

**Comment by singledigit** [comment]
ok, scratch that.. I needed to run the 6.10. Proper command for me was...
```
docker run -v "$PWD":/var/task lambci/lambda:nodejs6.10
```

**Comment by whummer** [comment]
Thanks @singledigit, support for 6.10 was still missing when you tested it. In the updated version you can now specify `nodejs6.10` as your Lambda runtime (see https://github.com/atlassian/localstack/commit/a240285226847cdc07caf07c913f3f54a0f6e135#diff-2dce34f36977e0b6398556134ff5f411R32). Closing this for now, please re-open if there are any more issues.

**Comment by andreiconstantinescu** [comment]
I tried this today... basically I ran `docker run -it -p 4567-4580:4567-4580 -p 8080:8080 atlassianlabs/localstack` and then tried to pipe in a simple nodejs handler and it immediately blew with an `SyntaxError: invalid syntax` around a constant, even though i usesd the `nodejs6.10` runtime.

```js
const docs = `bla bla ${variable}`
```
What am i doing wrong?

**Comment by singledigit** [comment]
So you call lambic directly. 
```
docker run -v "$PWD":/var/task lambci/lambda:nodejs6.10
```
For that you don't even need local stack. However, you can link into local stack with something like
```
docker run --link <localstack-container> -v "$PWD":/var/task lambci/lambda:nodejs6.10
```
That will allow you to connect to the local stack services. I would love to see an example of configuring local stack lambda to call on lambic.

**Comment by andreiconstantinescu** [comment]
i was hoping to use the `aws --endpoint-url=http://localhost:4574 lambda create-function` cli tool... i'll try your way to check it out
