### ISSUE TITLE
Support for redshift 

### ISSUE THREAD

**Issue by eyadsibai** [atlassian/localstack#28]
Not sure if it's possible but it would be great to have redshift support

**Comment by whummer** [comment]
Basic support for Redshift is added in #29 . Note that the mock functionality only covers the basic Redshift API methods (a subset of https://docs.aws.amazon.com/redshift/latest/APIReference/). The actual query capabilities (i.e., accessing Redshift via JDBC) are not supported here (at this stage it is not feasible to mock the entire query engine).
