### ISSUE TITLE
Make startup services and ports configurable via Docker

### ISSUE THREAD

**Issue by whummer** [atlassian/localstack#30]
Currently the Docker container spins up the default configuration which covers the entire set of services.

We should add a configuration option (e.g., environment variable) that can be passed to the container to customize the set of services to be spun up. Also the local port range should be configurable.

**Comment by Chyroc-MD** [comment]
+1 ！ 

only s3 needed.

**Comment by DFoxinator** [comment]
+1

**Comment by mlebrun** [comment]
+1

**Comment by ingluisjimenez** [comment]
+1 definitely makes sense to be able to spin up only specific services.

**Comment by eugenebond** [comment]
+1

**Comment by be-dmitry** [comment]
+1

**Comment by whummer** [comment]
Fyi, this one is in progress. Should be released soon.

**Comment by ingluisjimenez** [comment]
@whummer much appreciated.

**Comment by whummer** [comment]
Fixed in version `0.3.9`: You can now specify the startup services/ports via the `SERVICES` environment variable. Please refer to the updated configuration section in the README: https://github.com/atlassian/localstack#configurations
