### ISSUE TITLE
disable github issues

### ISSUE THREAD

**Issue by jdc0589** [atlassian/localstack#33]
the readme looks like you guys don't want issues or anything opened up here, and just want to treat this repo as a mirror. You probably want to disable github issues to avoid confusion.

**Comment by arun-gupta** [comment]
Please make sure the issue tracker on bitbucket repo is enabled before you close the issue tracker here. There is no way to report issues otherwise.

**Comment by whummer** [comment]
Thanks for the hint, issue tracking on Bitbucket is now enabled.
