### ISSUE TITLE
Cloudformation

### ISSUE THREAD

**Issue by slapula** [atlassian/localstack#38]
Are there any plans to support Cloudformation at any point?

**Comment by whummer** [comment]
No immediate plans at the moment, but we can look into it. (Apologies, but we currently only have limited resources to maintain this project.)

Before adding support for new APIs, we need to work on the ability to customize the services (i.e., configure which services/APIs should be spun up, especially when running in Docker). See https://github.com/atlassian/localstack/issues/30

I'll keep this ticket open so we don't forget about adding CloudFormation support in the near future.

**Comment by pchaganti** [comment]
👍

**Comment by whummer** [comment]
Initial support for CloudFormation has been added in version `0.3.11`. The new Docker image for that version will be pushed to Docker Hub shortly.
