### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by mainanick** [atlassian/localstack#39]
Collecting localstack
  Downloading localstack-0.3.2.tar.gz (282kB)
    100% |################################| 286kB 677kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\#####\AppData\Local\Temp\pip-build-ei7ef_g0\localstack\setup.py", line 40
        **print e.output**
              ^
    **SyntaxError: Missing parentheses in call to 'print'**

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in **C:\Users\#####\AppData\Local\Temp\pip-build-ei7ef_g0\localstack\**

Using  Python 3.5.2

**Comment by Chyroc-MD** [comment]
maybe installed by py2 and you use py3,so some error happen.

**Comment by KarlHarnois** [comment]
I'm having the same issue, all my other `requirements.txt` dependencies are installed with the correct version.

**Comment by gileadslostson** [comment]
In the `README` it states that `Python 2` is required unfortunately.

**Comment by whummer** [comment]
Unfortunately, only Python 2 is currently supported. There is currently no ETA for Python 3 support, as we would first have to analyze which parts of the code base are affected by incompatibility with version 3.

That said, I've started a draft document to keep track of the status of Python 3 compatibility, and I welcome everybody to contribute to the migration effort: https://bitbucket.org/atlassian/localstack/src/master/doc/python3_compatibility/ Thanks
