### ISSUE TITLE
Issue with notifications on S3

### ISSUE THREAD

**Issue by andreicek** [atlassian/localstack#42]
Hello,

I'm trying to configure S3 to SQS notifications. As per AWS configuration, this is as simple as:

```bash
aws s3api put-bucket-notification-configuration --bucket my-bucket --notification-configuration file://notification.json
```

So I've created a bucket:

```bash
aws --endpoint-url=http://localhost:4572 s3 mb s3://my-bucket
```

And an SQS queue:

```bash
aws --endpoint-url=http://localhost:4576 sqs create-queue --queue-name my-bucket-create
```

And a `config.json` file:

```javascript
{
    "QueueConfigurations": [
        {
            "QueueArn": "http://localhost:4576/123456789012/test",
            "Events": [
                "s3:ObjectCreated:*"
            ]
        }
    ]
}
```

And nothing fails, but when I create an object there are no messages on SQS.

Thanks!

**Comment by whummer** [comment]
Support for bucket notifications fixed in 5f0304d734abb3d7a7e03ed30787464dabad441a . Please confirm that it works for you @andreicek , otherwise re-open this ticket if the problem persists. Thanks.

**Comment by andreicek** [comment]
Hi,

Can you please tell me how you tested this? By issuing commands that I specified above this is not working.

```bash
aws --endpoint-url=http://localhost:4572 s3 mb s3://my-bucket
aws --endpoint-url=http://localhost:4576 sqs create-queue --queue-name my-bucket-create
aws --endpoint-url=http://localhost:4572 s3api put-bucket-notification-configuration --bucket my-bucket --notification-configuration file://notification.json
```

And the contents of `notification.json` are:

```javascript
{
  "QueueConfigurations": [
    {
      "QueueArn": "http://localhost:4576/123456789012/my-bucket-create",
        "Events": [
          "s3:ObjectCreated:*"
        ]
    }
  ]
}
```

Docker image I'm using is tagged as `latest` and pulled a few minutes ago.

**Comment by whummer** [comment]
@andreicek apologies, the `latest` tag was still pointing to the old image. This has now been updated, please pull again.

I was able to test this successfully with your exact commands, plus two additional commands, see below:
```
aws --endpoint-url=http://localhost:4572 s3 mb s3://my-bucket
aws --endpoint-url=http://localhost:4576 sqs create-queue --queue-name my-bucket-create
aws --endpoint-url=http://localhost:4572 s3api put-bucket-notification-configuration --bucket my-bucket --notification-configuration file://notifications.json
aws --endpoint-url=http://localhost:4572 s3 cp /tmp/test-file.txt s3://my-bucket/test-object
aws --endpoint-url=http://localhost:4576 sqs receive-message --queue-url http://localhost:4576/123456789012/my-bucket-create
```

**Comment by andreicek** [comment]
Works as expected! I didn't include the upload command but I did that.

Thanks!

**Comment by kprzerwa-r7** [comment]
I don't seem to be able to make the bucket notifications work. Docker image version: `0.7.1`
My configuration is similar to the one supplied by @andreicek, but I am getting errors on both SQS and SNS notification attempts (on create object even).
SNS error:
```
ERROR:localstack.services.generic_proxy:Error forwarding request: 'dict' object has no attribute 'split' Traceback (most recent call last):
  File "/home/kprzerwa/localstack/localstack/services/generic_proxy.py", line 131, in forward
    data=data, headers=forward_headers, return_forward_info=True)
  File "/home/kprzerwa/localstack/localstack/services/sns/sns_listener.py", line 22, in update_sns
    req_data = urlparse.parse_qs(data)
  File "/usr/lib/python2.7/urlparse.py", line 383, in parse_qs
    for name, value in parse_qsl(qs, keep_blank_values, strict_parsing):
  File "/usr/lib/python2.7/urlparse.py", line 409, in parse_qsl
    pairs = [s2 for s1 in qs.split('&') for s2 in s1.split(';')]
AttributeError: 'dict' object has no attribute 'split'

WARNING:localstack.services.s3.s3_listener:Unable to send notification for S3 bucket "<bucket-name>" to SNS topic "arn:aws:sns:us-east-1:123456789012:<queue-name>".
```
SQS error:
```
WARNING:localstack.services.s3.s3_listener:Unable to send notification for bucket "<bucket-name>" to SQS queue "arn:aws:sqs:us-east-1:123456789012:<queue-name>".
```

The warning message does not give any reason. I don't need to set policies on my topics and queues to allow the bucket to publish notifications/send messages, do I? Any ideas @whummer?

**Comment by kprzerwa-r7** [comment]
Why do we provide queue URL for queue ARN value when setting up S3 notification to sqs? This is what caused my most recent confusion when notifications were unable to be sent to the queue. I've been getting an error:
```
WARNING:localstack.services.s3.s3_listener:Unable to send notification for bucket "bucket-name" to SQS queue "arn:aws:sqs:us-east-1:123456789012:queue-name".
```
...then I noticed that @andreicek's configuration has queue URL in place of QueueArn. I updated my configuration and I was able to receive notifications. Is it issue with localstack, or does it happen with AWS too?

**Comment by whummer** [comment]
Great catch @kprzerwa-r7 , thanks for flagging this! This has been fixed. Also the tests have been updated to use Queue ARN instead of URL: https://github.com/localstack/localstack/blob/453d4548301bed97fcf8a3bd8181c5eaeade254a/tests/integration/test_notifications.py#L70

The Docker image is currently being built and pushed: https://travis-ci.org/localstack/localstack/builds/257295115

Please note @andreicek that this might be a breaking change for your configuration. However, the new behavior is the correct one in terms of equivalence with the AWS API.

**Comment by kprzerwa-r7** [comment]
Thanks for the fix @whummer!

I also found that setting bucket notification configuration does not work through java sdk.
From what I can see, `awscli` sends PUT request to `http://localhost:4572/<bucket-name>?notification`, while `AmazonS3` in AWS SDK will send the notification to `http://<bucket-name>.<endopoint>/?notification`. This means that configuration done through java sdk does not get applied.
See http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTnotification.html

**Comment by whummer** [comment]
This could be related to: https://github.com/localstack/localstack#troubleshooting . You may need to set `setPathStyleAccess(true)` on your S3 options to get this working. This is one of the current limitations which we might be able to fix in the future if we use a custom DNS configuration.

**Comment by kprzerwa-r7** [comment]
Indeed it was @whummer! Thanks :+1:
