### ISSUE TITLE
ElasticSearch ConnectionError

### ISSUE THREAD

**Issue by GianlucaBortoli** [atlassian/localstack#46]
After building the Docker image by myself, I try to launch the whole stack and ElasticSearch gives me the following error:

`
('check_infra_elasticsearch exception', ConnectionError('N/A', "HTTPConnectionPool(host='localhost', port=4571): Max retries exceeded with url: /_aliases (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f64882a74d0>: Failed to establish a new connection: [Errno 111] Connection refused',))", ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=4571): Max retries exceeded with url: /_aliases (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f64882a74d0>: Failed to establish a new connection: [Errno 111] Connection refused',))",),)))
` 

If I exclude ES to be provisioned in the stack, eveything works fine.
The entire stack (ES included) works if I pull the image from the Docker hub.

Any guess what may cause it?

**Comment by whummer** [comment]
Is this still an issue? The image builds fine in the CI environment (Bitbucket pipelines): https://bitbucket.org/atlassian/localstack/addon/pipelines/home
I'm closing this ticket for now, please re-open if the problem still occurs: @GianlucaBortoli

**Comment by ijcd** [comment]
Seeing this when pulling the prebuilt image from dockerhub.

**Comment by rifflock** [comment]
I'm also seeing this from the prebuilt image, just like @ijcd
