### ISSUE TITLE
Dockerfile for base image

### ISSUE THREAD

**Issue by cliftbar** [atlassian/localstack#50]
I've been looking around and can't find a Dockerfile for the base image (fancylinq/alpine-oraclejdk8-mvn).  It would be nice to know what this is image getting built off of.

**Comment by whummer** [comment]
Good point, we should not be using this custom image. I'm preparing a PR to use the official `maven:alpine` image instead (it provides the same features).

**Comment by whummer** [comment]
Fixed in e4d3e6ab18d3c2d45acaa415699eec3328a53f5a
