### ISSUE TITLE
 S3 whether to support ssl？

### ISSUE THREAD

**Issue by jinghuaz** [atlassian/localstack#55]
There is no configuration can let s3 support ssl or use proxy？

**Comment by whummer** [comment]
No, using SSL for the mock APIs is not supported unfortunately. Is this a major blocker for you, i.e., how exactly are you accessing the S3 API, and what kind of error do you get if SSL is not enabled?

This is currently not high up in the priority list, but I'd be happy to accept a pull request if you have a solution that easily integrates with the existing code base.

**Comment by whummer** [comment]
I'm closing this issue for now. @jinghuaz Please provide more details around your use case. Once we have a better understanding of the concrete requirements, we can re-open the ticket.

**Comment by jinghuaz** [comment]
ok,thank you @whummer , now I used nginx to solve the problem with HTTPs.
