### ISSUE TITLE
API Gateway get-api-keys return 404

### ISSUE THREAD

**Issue by dtrifonov** [atlassian/localstack#57]
Hello Guys,
I am trying to create an api gateway endpoint using localstack. I am using aws-cli and I have successfully executed commands - create-rest-api, get-resources and put-method. 

When I try to execute the command: get-api-keys, the server returns:
```
aws apigateway get-api-keys --endpoint http://localhost:4567 --profile my_aws_profile
```

```
An error occurred (404) when calling the GetApiKeys operation: <!DOCTYPE HTML PUBLIC"-//W3C//DTD HTML 3.2 Final//EN"><title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
```
My question is if all aws-cli commands for api gataway service are supported in localstack?

**Comment by whummer** [comment]
Hi, unfortunately API Keys are currently not supported in the API Gateway mock. We are using `moto` as the underlying mock, you can see the supported API endpoints here: https://github.com/spulec/moto/blob/master/moto/apigateway/urls.py
Please open a ticket against that repo, or ideally provide a pull request directly. Thanks

**Comment by dtrifonov** [comment]
Hello Whummer,
Thanks for the feedback. Actually I found a suitable service for my case:
```
aws apigateway get-rest-apis --endpoint=http://localhost:4567 --profile=my_aws_profile
```

I will close the issue.

**Comment by haydenth** [comment]
I'm still having this issue when invoking the get_api_keys call from boto3

```
  client = boto3.client('apigateway', use_ssl=False,
                        endpoint_url="http://taft-localstack:4567")
  response = client.get_api_keys(includeValues=True)
```

Throws
```
ClientError: An error occurred (404) when calling the GetApiKeys operation: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"> <title>404 Not Found</title> <h1>Not Found</h1> <p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
```

**Comment by haydenth** [comment]
Looks like it has been added upstream in moto! Hooray

https://github.com/spulec/moto/blob/master/moto/apigateway/models.py#L594
