### ISSUE TITLE
LocalstackTestRunner: getEndpointSQS() points to "sns"

### ISSUE THREAD

**Issue by terrysdev9** [atlassian/localstack#65]
I was trying out the LocalstackTestRunner in JUnit and was unable to get SQS client working against the localstack endpoint. Turns out the getEndpointSQS() method references "sns". I made the change to "sqs", rebuilt the artifact, and I get the expected results. Can you please provide a quick fix for this? I have the code change including a unit test if you want it. Thanks!

**Comment by whummer** [comment]
Thanks for the bug report @terrysdev9 , would you be able to raise a pull request (PR) with your changes? Please raise the PR against the main repository on Bitbucket: https://bitbucket.org/atlassian/localstack Thanks

**Comment by terrysdev9** [comment]
@whummer Not a problem. However, I don't have permission when I try to push my branch onto the repo using my 'terrysdev9' credentials. Here's the output:

=> git push origin bug/sqs
Username for 'https://bitbucket.org': terrysdev9
Password for 'https://terrysdev9@bitbucket.org': 
remote: Unauthorized
fatal: Authentication failed for 'https://bitbucket.org/atlassian/localstack.git/'

**Comment by whummer** [comment]
Fixed in 5f0304d734abb3d7a7e03ed30787464dabad441a
