### ISSUE TITLE
Nodejs Lambda functions?

### ISSUE THREAD

**Issue by andreiconstantinescu** [atlassian/localstack#66]
Is there any plan to support nodejs files as lambda functions? 
I can't get it to work with a `.js` handler :( 

Thanks,
Andrei

**Comment by whummer** [comment]
Currently, only Python Lambdas are supported unfortunately. But there has been a proposal to use a Docker image from *lambci* to execute the Lambdas: https://github.com/atlassian/localstack/issues/27 We will be looking into this shortly.

**Comment by whummer** [comment]
@andreiconstantinescu Initial/experimental support for nodejs lambdas (executed in a separate Docker container) has been added. Please refer to this comment and give it a try: https://github.com/atlassian/localstack/issues/27#issuecomment-297616262

**Comment by andreiconstantinescu** [comment]
Thanks @whummer, I'll give it a try and see how it goes.

**Comment by whummer** [comment]
Closing this for now, please re-open if there are still any issues executing Nodejs Lambda functions.
