### ISSUE TITLE
CORS-support in s3

### ISSUE THREAD

**Issue by ostronom** [atlassian/localstack#69]
Looks like, the current implementation of S3 module does not support CORS in any way. I've tried to set CORS on a bucket using cli, it responds w/o error, but no CORS are actually set -- i can't get them via get-bucket-cors and i see js-exceptions when i'm trying to use signed urls from aws API. The same behaviour holds when i'm trying to do this via java API.

Are there any plans to add CORS support?

**Comment by whummer** [comment]
Added CORS support for S3 in 27fb4050c8a14f303409882bbfc440d4a91e9af1 . The change has also been pushed to the most recent Docker image (`atlassianlabs/localstack:0.3.11`). Can you please give it a try and report here whether it worked? Thanks

**Comment by whummer** [comment]
@ostronom did you have a chance to give this a try?

**Comment by whummer** [comment]
Closing this as fixed, please re-open if the problem persists.
