### ISSUE TITLE
Could not retrieve uploaded file from S3

### ISSUE THREAD

**Issue by ambrusadrianz** [atlassian/localstack#70]
Steps to reproduce the issue: upload image to s3 -> try to access it from the browser

The error I get by the Docker container:

`ERROR:localstack.mock.generic_proxy:Error forwarding request: Traceback (most recent call last):
  File "/opt/code/localstack/localstack/mock/generic_proxy.py", line 104, in forward
    self.wfile.write(response.text)
  File "/usr/lib/python2.7/socket.py", line 320, in write
    data = str(data) # XXX Should really reject non-string non-buffers
UnicodeEncodeError: 'ascii' codec can't encode character u'\x89' in position 0: ordinal not in range(128)`

**Comment by whummer** [comment]
Thanks for reporting this bug. This is fixed in commit 72890ce36ad7c1be0c0eac8f78dbfee06ab0b769

The Docker image (tags `0.3.10` and `latest`) has been updated, if you pull the image again it should work. Please re-open if the problem persists.
