### ISSUE TITLE
Upgrade to latest moto

### ISSUE THREAD

**Issue by ambrusadrianz** [atlassian/localstack#74]
I saw that LocalStack is already using moto-ext which is maintained by @whummer. So the question is, could you upgrade that version and use that until an official moto version is released? It would be really appreciated.

**Comment by whummer** [comment]
Latest moto code included in `moto-ext`, bumped to version `0.3.11` of *LocalStack*. The new Docker image for that version will be pushed to Docker Hub shortly.
