### ISSUE TITLE
Enable persistent data storage for S3 (and potentially other services)

### ISSUE THREAD

**Issue by tomhallam** [atlassian/localstack#77]
Hey, thanks for this useful tool.

What volumes do we need to set up for persistence of Dynamo, S3, etc? We would like data to survive restarts.

Cheers

**Comment by whummer** [comment]
Hi @tomhallam , that is a good question. Currently, we can support persistence for Kinesis, DynamoDB, and Elasticsearch. I will add a PR and some documentation shortly. The other APIs are mostly in-memory and persistent state will be a bit harder to achieve.

One possible solution though, could be to record the API calls, persist them to disk, and then replay the exact same API calls in the right order when restarting the container. This approach should would work for arbitrary APIs and could be handy to persist/reproduce any kind of state.

**Comment by whummer** [comment]
Initial support for persistence added in 97142569daf41e49525f43cce49cf63624dc21e4 . Currently works only for the services DynamoDB/Kinesis/Elasticsearch, support for S3 to follow soon. Please let me know whether that works for you @tomhallam .

To support persistence for all other services, we could implement the generic record-and-replay approach described in the comment above, but that is a mid-/long-term effort that we should probably track in a separate ticket.

**Comment by tomhallam** [comment]
@whummer thanks for your help on this! I will test it with our setup, but it seems like it'll be fine. Let me know when S3 support is rolled out too :)

**Comment by whummer** [comment]
@tomhallam Initial support for S3 persistence added in commit 0ab387b75472cc73843907b58c66e7a305937b73 . The implementation uses the approach based on record/replay of API calls. Simply set the environment variable `DATA_DIR` to a folder on the local disk (e.g., `DATA_DIR=/tmp/localstack/data`) to enable this feature.
