### ISSUE TITLE
Add 'sequenceNumber' to Kinesis events

### ISSUE THREAD

**Issue by vigowei** [atlassian/localstack#85]
```"Records": [
    {
      "eventID": "xyz:123",
      "eventVersion": "1.0",
      "kinesis": {
        "partitionKey": "partitionKey",
        "data": "encoded_data",
        "kinesisSchemaVersion": "x.x",
        "sequenceNumber": "49545115243490985018280067714973144582180062593244200961"
      },
      "invokeIdentityArn": ...
    }
  ]
}
```

In actual events published by Kinesis, the records have four fields: `data`, `partitionKey`, `kinesisSchemaVersion` and `sequenceNumber`, right now kinesis events in localstack only contain `data` and `partitionKey`, don't think the schema version matters as much but some apps do track `sequenceNumber`, it would be really nice to add that field to make events more realistic and useful.

**Comment by whummer** [comment]
Thanks for reporting. This is fixed in 363196aeec34fd45c9bfe8c31939591ec46521af
