### ISSUE TITLE
Lambda: create_function should fail when function name exists

### ISSUE THREAD

**Issue by vigowei** [atlassian/localstack#90]
Per AWS documentation for [CreateFunction](http://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html): 

> If the function name already exists, the operation will fail.

Currently you can create a function with the same name more than once, and all of them will process events from configured event source(s), as a result, those events are being processed multiple times.

**Comment by whummer** [comment]
Thanks for reporting. Fixed in 39108b7d291b1a98e4c1be5010120d437966a513
