### ISSUE TITLE
Improve dynalite performance

### ISSUE THREAD

**Issue by nitely** [atlassian/localstack#92]
dynalite changes are [being written to disk](https://github.com/atlassian/localstack/blob/6adab2d2d919380b9926df2cef6bcfa38dcadc86/localstack/mock/infra.py#L49) instead of being just in-memory. Removing the `--path` option should fix it. Any reason why this is not the default?

dynalite has some [pretty crazy defaults](https://github.com/mhart/dynalite#example) for creating/deleting/updating tables, for no good reason at all. Default is currently 500ms. There is no reason at all for such a thing. If one is trying to test CREATING/DELETING/etc status then that waiting time should be set to forever/infinite. Setting the waiting time to 500ms just makes things slow when trying to recreate tables for every test (ie: to remove all data from them)

**Comment by whummer** [comment]
Thanks for suggesting this improvement. Fixed in 1351870a6846998cf8a6f3c1cc49327b50c8f6e3, released in version `0.4.1`.
