### ISSUE TITLE
Can't upload java lambda code

### ISSUE THREAD

**Issue by bgrgl** [atlassian/localstack#97]
Is it possible to upload java lambda code?
I'm using localstack in a docker container and each time I'm trying to upload my lambda code via aws cli the localstack's log returns something like:

> WARNING:localstack.mock.apis.lambda_api:Content of Lambda archive: total 7824
drwxr-xr-x    4 root     root          4096 May  8 15:35 .
drwxrwxrwx    1 root     root          4096 May  8 15:35 ..
drwxr-xr-x    3 root     root          4096 May  8 15:35 com
drwxr-xr-x    2 root     root          4096 May  8 15:35 lib
-rw-r--r--    1 root     root       7992222 May  8 15:35 original_lambda_archive.zip
ERROR:lambda_mock:Exception on /2015-03-31/functions [POST]
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/localstack/localstack/mock/apis/lambda_api.py", line 329, in create_function
    set_function_code(code, lambda_name)
  File "/opt/code/localstack/localstack/mock/apis/lambda_api.py", line 281, in set_function_code
    raise Exception('Unable to find handler script in Lambda archive.')
Exception: Unable to find handler script in Lambda archive.

My cli command looks like following:

> aws --endpoint-url=http://localhost:4574 lambda create-function \
--region us-east-1 \
--function-name HelloLambda \
--zip-file fileb://LambdaTest-1.0-SNAPSHOT.zip \
--role helloRole \
--handler com.example.LambdaTest::handleLambdaTestRequest \
--runtime java8 \
--timeout 2

Despite that I tried to upload my function via s3 bucket. My attempt was successful, but each invocation of function via aws cli returned code 200, but function seems didn't work because I did not receive for that invocation.

The web dashboard LambdaNode -> Show Code showed no code for both cases.

Does anybody have any suggestions for this case?

**Comment by gabor-nagy** [comment]
Not sure it helps in your case but I first tried to zip the jar file and got the same error while uploading. Uploading the jar directly seems to work, but when I try to invoke it, I also get a 200 status code via the CLI. The localstack log says:

`ERROR: 'java -cp /opt/code/localstack/localstack/mock/target/lambda-executor-1.0-SNAPSHOT.jar:/tmp/localstack/lambda.handler.837adbd3.jar com.atlassian.LambdaExecutor com.helloworld.jpdfc.aws.lambda.JpdfcHandler /tmp/localstack/lambda.event.89e33503.json': Error: Could not find or load main class com.atlassian.LambdaExecutor

ERROR executing Lambda function: Traceback (most recent call last):
  File "/opt/code/localstack/localstack/mock/apis/lambda_api.py", line 182, in run_lambda
    result = func(event, context)
  File "/opt/code/localstack/localstack/mock/apis/lambda_api.py", line 265, in execute
    output = run(cmd)
  File "/opt/code/localstack/localstack/utils/common.py", line 311, in run
    return do_run(cmd)
  File "/opt/code/localstack/localstack/utils/common.py", line 308, in do_run
    raise e
CalledProcessError: Command 'java -cp /opt/code/localstack/localstack/mock/target/lambda-executor-1.0-SNAPSHOT.jar:/tmp/localstack/lambda.handler.837adbd3.jar com.atlassian.LambdaExecutor com.helloworld.jpdfc.aws.lambda.JpdfcHandler /tmp/localstack/lambda.event.89e33503.json' returned non-zero exit status 1
`

**Comment by gabor-nagy** [comment]
@bgrgl I checked the source code and I see "TODO: Support for AWS Lambda functions written in Java is work in progress." at https://github.com/atlassian/localstack/blob/master/ext/java/src/main/java/com/atlassian/localstack/LambdaExecutor.java

**Comment by bgrgl** [comment]
@gabor-nagy Thanks a lot for the information. Hope it will be available soon.

**Comment by whummer** [comment]
@bgrgl @gabor-nagy Initial support for Java Lambda functions has been added in version `0.4.2` (currently working for Kinesis events only).

There is a simple integration test which uses this Lambda handler class: https://github.com/atlassian/localstack/blob/master/localstack/ext/java/src/test/java/com/atlassian/localstack/sample/KinesisHandler.java 

It gets deployed as part of this test:
https://github.com/atlassian/localstack/blob/master/tests/integration/test_integration.py#L168

Note that the file type issue has been fixed - the mock API now expects a JAR file that is wrapped in a ZIP file. Please give it a go an let me know if it works for you.

Side note: Java Lambdas can only be executed on the local host directly (`LAMBDA_EXECUTOR=local`), execution inside a Docker container (`LAMBDA_EXECUTOR=docker`) is currently not available until this upstream issue is fixed: https://github.com/lambci/docker-lambda/issues/1

**Comment by whummer** [comment]
Closing this issue as fixed. Please re-open if the problem persists.
